version: '3'

services:
  nginx:
    container_name: "server"
    image: nginx
    volumes:
      - ./static/:/usr/share/nginx/html/
      - ./nginx/:/etc/nginx/
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80  