version: "3"

services:
  nginx:
    container_name: "server"
    image: nginx
    volumes:
      - ./static/:/usr/share/nginx/html/
      - ./nginx/:/etc/nginx/
    ports:
      - 80:80
      - 443:443
    # environment:
    # - NGINX_PORT=80
    # - NGINX_PORT=443

  app1:
    container_name: app1
    build: ./server/
    ports:
      - 3001:3001
    environment:
      - PORT=3001

  app2:
    container_name: app2
    build: ./server/
    ports:
      - 3002:3002
    environment:
      - PORT=3002

  app3:
    container_name: app3
    build: ./server/
    ports:
      - 3003:3003
    environment:
      - PORT=3003
